### ISSUE TITLE
iOS6 Support

### ISSUE THREAD

**Issue by keplersj** [k3a/AssistantExtensions#2]

**Comment by Tatsh** [comment]
Crashes on iOS 6 intermittently. Brightness control works, but then crashes. ChatBot crashes after attempting to start the conversation.

**Comment by keplersj** [comment]
I've noticed that anything attempting to open view crashes. My own plugins, Lingual, etc. The only snippet that seems to work is YouTube search.

**Comment by k3a** [comment]
I am working on iOS6 compatibility. After it's finished (I estimate a week or two) all existing extensions will work. In this update, I am also rewriting IPC communication from CPDistributedMessagingCenter to mach-o IPC which will solve brightness problems and freezing. Thanks for your patience.

**Comment by keplersj** [comment]
What is the progress report on this? Not to pressure you or anything, I am just wondering where the update is going along. Did you encounter issues with the update? Are you ok?

**Comment by keplersj** [comment]
I would hate to see this amazing tweak/framework die, as it did re-shape how people imagined Siri Tweaks in iOS 5. This was the stepping stone that really got me starting with Objective-C.

**Comment by k3a** [comment]
It's still work-in-progress and definitely not going to die anytime soon. It takes longer because I need to update my other tweaks as well in the meantime. Thanks for the patience.

**Comment by Paliverse** [comment]
well my friend you need to find other developers that will work with you. ones that you can talk to about get help and all that other stuff. i wish i knew how to develop as i am learning objective-c at the moment but its REALLY HARD to understand all of theses codes and what they mean and why do this and that. the place that i learn does not explain every single details. so until i become as good as you i shall help you with updates on all your tweaks.

**Comment by biscuitehh** [comment]
I know issues come up and I hate to be THAT guy, but is this still being worked on?

**Comment by keplersj** [comment]
Don't worry I was THAT GUY a couple months ago.
—

**Comment by k3a** [comment]
Hi all! I have released ios6-compatible pre-release on my repo http://k3a.me/c/ . Thanks for your patience and sorry for waiting forever but official release is coming very soon. In the pre-release, Siri guide integration is not update yet. Other functions and extensions should work as before.

**Comment by Tatsh** [comment]
Does this mean 'let's chat' is not working yet?

**Comment by k3a** [comment]
Let's chat works. :) What doesn't work is adding an extension to the siri guide - this thing http://maypalo.com/wp-content/uploads/2011/10/iPod-touch-Siri.png

**Comment by Tatsh** [comment]
Glad to hear. Do I have to just wait a while the first time using Chatbot?

**Comment by k3a** [comment]
Yep, after you say let's chat you need to wait until it loads all AIML definitions. It can be sped by removing some definitions but the more definitions are loaded the more topics can be "talked about". If I find some time, I will add topic selection to Settings so you will be able to enable only those you are interested in and speed up the loading...

**Comment by autumnt856** [comment]
Is there a particular server this works on? I'm using SiriDR and I have an iPhone 4 running 6.1.2. I also installed the pre-released version, but still can't get it to run. Thanks.

**Comment by keplersj** [comment]
Not our issue.

**Comment by autumnt856** [comment]
Ok...
